environment: {}
parameters: {}
packages:
  - name: bubbles
    environment: {}
    parameters: {}
    annotations: {}
    actions:
      - name: add
        main: ''
        runtime: 'go:default'
        parameters: {}
        environment: {}
