environment: {}
parameters: {}
packages:
  - name: bubbles
    environment: {}
    parameters: {}
    annotations: {}
    functions:
      - name: add
        binary: false
        main: ''
        runtime: 'go:default'
        web: true
        parameters: {}
        environment: 
          GH_PAT: "${GH_PAT}"
        annotations: {}
        limits: {}
